# Generated by Django 5.1.2 on 2024-10-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0003_alter_reservation_options_alter_ticket_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='duration',
            field=models.IntegerField(default=None),
        ),
    ]
