# Generated by Django 5.1.2 on 2024-10-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0004_play_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
