# Generated by Django 5.1.2 on 2024-10-11 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0005_alter_play_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='play',
            old_name='actor',
            new_name='actors',
        ),
        migrations.RenameField(
            model_name='play',
            old_name='genre',
            new_name='genres',
        ),
    ]
